import path from 'path';
import { Plugin } from 'vite';

/**
 * Plugin to support Alloy Widgets
 */
export function widgetPlugin(appDir: string): Plugin {
	return {
		name: 'titanium:alloy:widgets',
		/**
		 * Resolves URLs generated by `WPATH` to their source files inside a
		 * Widget's `lib` directory.
		 *
		 * @todo: Support Widgets from `node_modules`.
		 */
		async resolveId(id, importer) {
			if (id.startsWith('/') && !id.startsWith(appDir)) {
				// check WPATH generated url `/<widget>/<id>`
				const secondSlashIndex = id.indexOf('/', 1);
				if (secondSlashIndex !== -1) {
					const widgetId = id.slice(1, secondSlashIndex);
					const relativeId = id.slice(secondSlashIndex + 1);
					const result = await this.resolve(
						path.join(appDir, 'widgets', widgetId, 'lib', relativeId),
						importer,
						{ skipSelf: true }
					);
					if (result) {
						return result.id;
					}
				}
			}
		}
	};
}
